u9

diff --git a/roles/mysql/tasks/main.yml b/roles/mysql/tasks/main.yml
--- a/roles/mysql/tasks/main.yml
+++ b/roles/mysql/tasks/main.yml
@@ -23,39 +23,45 @@
     enabled: true    
     daemon_reload: yes 
 
+- name: DEFAULT_PASSWORD 
+  ansible.builtin.shell: grep 'A temporary password' /var/log/mysqld.log | cut -d " " -f 11
+  register: out 
+
+- name: get the uptime data from defined variable
+  ansible.builtin.debug:
+  msg: "{{out.stdout}}"  
+
+# DEFAULT_PASSWORD=$(grep 'A temporary password' /var/log/mysqld.log | cut -d " " -f 11)
 
 
-DEFAULT_PASSWORD=$(grep 'A temporary password' /var/log/mysqld.log | cut -d " " -f 11)
+#  echo " ALTER USER 'root'@'localhost' IDENTIFIED BY '$1';
+# FLUSH PRIVILEGES; " > /tmp/set-root-passwd.sql
 
 
- echo " ALTER USER 'root'@'localhost' IDENTIFIED BY '$1';
-FLUSH PRIVILEGES; " > /tmp/set-root-passwd.sql
+# echo "show databases;" | mysql --connect-expired-password -uroot -p${DEFAULT_PASSWORD}
+# if [ $? -ne 0 ]; then 
+# echo " change the default password"
+# mysql --connect-expired-password -uroot -p${DEFAULT_PASSWORD} < /tmp/set-root-passwd.sql 
+# #&>>$LOG_FILE
+# #Statuscheck $?
+# echo " uninstall plugin validate_password; " | mysql -uroot -p$1 &>>$LOG_FILE
+# Statuscheck $?
+# fi 
 
+# echo " cleanup before installation"
+# rm -rf /tmp/mysql.zip &>>$LOG_FILE
+# Statuscheck $?
+# rm -rf /tmp/mysql-main &>>$LOG_FILE
+# Statuscheck $?
 
-echo "show databases;" | mysql --connect-expired-password -uroot -p${DEFAULT_PASSWORD}
-if [ $? -ne 0 ]; then 
-echo " change the default password"
-mysql --connect-expired-password -uroot -p${DEFAULT_PASSWORD} < /tmp/set-root-passwd.sql 
-#&>>$LOG_FILE
-#Statuscheck $?
-echo " uninstall plugin validate_password; " | mysql -uroot -p$1 &>>$LOG_FILE
-Statuscheck $?
-fi 
+# echo "download the database"
+# curl -s -L -o /tmp/mysql.zip "https://github.com/roboshop-devops-project/mysql/archive/main.zip" &>>$LOG_FILE
+# Statuscheck $?
 
-echo " cleanup before installation"
-rm -rf /tmp/mysql.zip &>>$LOG_FILE
-Statuscheck $?
-rm -rf /tmp/mysql-main &>>$LOG_FILE
-Statuscheck $?
-
-echo "download the database"
-curl -s -L -o /tmp/mysql.zip "https://github.com/roboshop-devops-project/mysql/archive/main.zip" &>>$LOG_FILE
-Statuscheck $?
-
-echo "Load the schema for Services"
-cd /tmp
-unzip mysql.zip
-cd mysql-main
-mysql -uroot -p$1 <shipping.sql  &>>$LOG_FILE
-Statuscheck $?
+# echo "Load the schema for Services"
+# cd /tmp
+# unzip mysql.zip
+# cd mysql-main
+# mysql -uroot -p$1 <shipping.sql  &>>$LOG_FILE
+# Statuscheck $?
 
