comment3

diff --git a/roles/common/tasks/app-prereq.yml b/roles/common/tasks/app-prereq.yml
--- a/roles/common/tasks/app-prereq.yml
+++ b/roles/common/tasks/app-prereq.yml
@@ -41,33 +41,33 @@
 
 
 
-APP_PREREQ() {
+# APP_PREREQ() {
 
-    echo " validate whether roboshop user is alreday exists or not"
-    id roboshop &>>${LOG_FILE}
+#     echo " validate whether roboshop user is alreday exists or not"
+#     id roboshop &>>${LOG_FILE}
 
-    if [ $? -ne 0 ]; then 
-    echo " adding user robohop to the VM "
-    useradd roboshop &>>${LOG_FILE}
-    Statuscheck $?
-    fi 
+#     if [ $? -ne 0 ]; then 
+#     echo " adding user robohop to the VM "
+#     useradd roboshop &>>${LOG_FILE}
+#     Statuscheck $?
+#     fi 
 
-    echo "Download ${COMPONENT} Application code"
-    curl -s -L -o /tmp/${COMPONENT}.zip "https://github.com/roboshop-devops-project/${COMPONENT}/archive/main.zip" &>>${LOG_FILE}
-    Statuscheck $?
+#     echo "Download ${COMPONENT} Application code"
+#     curl -s -L -o /tmp/${COMPONENT}.zip "https://github.com/roboshop-devops-project/${COMPONENT}/archive/main.zip" &>>${LOG_FILE}
+#     Statuscheck $?
 
-    echo "stoping the service before cleanup"
-    systemctl stop ${COMPONENT}.service
+#     echo "stoping the service before cleanup"
+#     systemctl stop ${COMPONENT}.service
 
-    echo " remove old content if exists - make the script compatable to re-run"
-    cd /home/roboshop && rm -rf ${COMPONENT}  &>>${LOG_FILE}
-    Statuscheck $?
+#     echo " remove old content if exists - make the script compatable to re-run"
+#     cd /home/roboshop && rm -rf ${COMPONENT}  &>>${LOG_FILE}
+#     Statuscheck $?
 
-    echo "extract the application "
-    unzip /tmp/${COMPONENT}.zip &>>${LOG_FILE}
-    Statuscheck $?
+#     echo "extract the application "
+#     unzip /tmp/${COMPONENT}.zip &>>${LOG_FILE}
+#     Statuscheck $?
 
 
-    mv ${COMPONENT}-main ${COMPONENT}
+#     mv ${COMPONENT}-main ${COMPONENT}
 
-}
+# }
